//
// Created by Badry Anas on 12/30/2025.
//

#ifndef FINALPROJECT_GENERATEGLOBALBUILDINGREPORTUSECASE_H
#define FINALPROJECT_GENERATEGLOBALBUILDINGREPORTUSECASE_H


class GenerateGlobalBuildingReportUseCase
{
};


#endif //FINALPROJECT_GENERATEGLOBALBUILDINGREPORTUSECASE_H