//
// Created by Badry Anas on 12/30/2025.
//

#ifndef FINALPROJECT_GENERATEMONTHLYBUILDINGREPORTUSECASE_H
#define FINALPROJECT_GENERATEMONTHLYBUILDINGREPORTUSECASE_H


class GenerateMonthlyBuildingReportUseCase
{
};


#endif //FINALPROJECT_GENERATEMONTHLYBUILDINGREPORTUSECASE_H